FROM node:13
MAINTAINER Grayden Shand graydenshand@gmail.com

RUN npm install react-scripts@3.4.1 -g --silent

## Copy and mount app
RUN mkdir /home/client
WORKDIR /home/client
COPY . /home/client/

RUN npm run build


# nginx server
FROM nginx
COPY build/ /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
ENTRYPOINT ["nginx"]
CMD ["-g", "daemon off;"]